using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Dogfly : MonoBehaviour  
{
    //每酌腌做一件事情-一timer不噙f增 timer=s t绦

    //物w\行一定要有速度!
    public float spd = 1.0f;
    //物w\行的半
    public float radius = 4.0f;
    //每酌腌D向?
    public float turninterval = 1.0f;
    //r器
    float timer;
   //o前方向
    Vector3 dir;
    //定x前位置
    Vector3 oPos;

    void Start()
    {
        //初始化SC方向 (-0.5的原因橐他在平面上SC移 )
        dir = new Vector3(Random.value - 0.5f, Random.value - 0.5f , 0);


    }

    
    void Update()
    {
        //如何\行物w? 位置D化-方向* 速度* rg
        transform.Translate(dir * spd * Time.deltaTime);
       //rg增加
        timer += Time.deltaTime;
        //如果rg>D向需求rg
        if(timer > turninterval)
        {
            //SCD向
            dir = new Vector3(Random.value - 0.5f, Random.value - 0.5f, 0);
            //rw零
            timer = 0;
        }


        //距x=三向量 距x
        float dist = Vector3.Distance(oPos, transform.position);
        if(dist > radius)
        {
            dir = -dir;
        }

    }
}
