using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//LuiM件需要@
using UnityEngine.UI;

public class L04_1029 : MonoBehaviour
{
    //新知Rc2-函抵剌d
    //意味著同悼梢杂薪邮芏不同档陌姹荆需要撰一名字相同，挡煌的函等缦

    private void fun1 (int a , int b)
    {

    }

    private void fun1 (float a)
    {

    }

    //新知R-字段修符:^大部分用砀淖在unity引擎中的@示方式
    //常用1-[SerializeField]private量也可以在引擎e面中@示
    //常用2-[HideInInspector]public量不在引擎中@示
    //常用3- [Range(0 ,10)] 改在引擎中@示的方式

    [SerializeField]private Rigidbody2D rb;
    [SerializeField] private Slider hpBar;
    //[SerializeField] private Sprite sp;
    public BoxCollider2D col;
    public float input_x;
    [HideInInspector]public bool input_y;
    [Range(0 ,10)]public int speed = 10;
    [Range(0, 30)] public float jumpforce = 1f;
    public bool isground;
    Animator anim;
    //明位子
    Vector3 oscale;
    private string npcTag = "NPC";
    private string traptag = "Trap";
    private string goodtrap = "GoodTrap";
    
   

    float maxHp = 100;
    float currentHp = 100; 

    //animator中常用的api-(1)animator.SetBool(string name , bool value) O定一bool的量
    //animator中常用的api-(2)animator.SetTrigger(string name , bool value) 激活一trigger的量
    //amimator.play(string statename)

    void Start()
    {
        //@取M件K⒋舜a燧d的D片成指定D片GetComponent<SpriteRenderer>().sprite = sp;
        anim = GetComponent<Animator>();
        //DQ於相於父物w的比例
        oscale = transform.localScale;

        float x = transform.position.x;
        float range = Mathf.Clamp(x, 0, 10);

      

    }

    private void Update()
    {
        GetInput();
        Move();
        Jump();
        Ray();
        Animation();
        //Moverange();
    }

    private void Animation()
    {
        //(在unity中transitionsO定的bool值string name , l件)
        anim.SetBool("Moving", input_x != 0);

    }

    private void Moverange()
    {
        float x = transform.position.x;
        float range = Mathf.Clamp(x, 0, 10);
        rb.transform.position = new Vector3(range, transform.position.y, transform.position.z);
    }


    private void Move()
    {
        rb.velocity = new Vector2(input_x * speed, rb.velocity.y);
        if (input_x > 0)
        {
            transform.localScale = new Vector3(oscale.x, oscale.y, oscale.z);
        }
         else if (input_x < 0)
        {
            transform.localScale = new Vector3(-oscale.x, oscale.y, oscale.z);
        }
       
        //自由-添加一蹲下的赢吧!

    }

    public void Jump()
    {
        //玩家在地板上 K且 按嚎瞻祖I
        if (isground && input_y )
        {
            //o予w往上增加一力 
            rb.AddForce(Vector2.up * 200 * jumpforce);
        }

    }

    private void Ray()
    {
        //取得此碰撞器底部位置的信息
        //Unity Bounds 边界框（包围盒） https://blog.csdn.net/qq_37524903/article/details/113625126
        //在三S向量中 有一origim 它的位置是 col.bounds.center(@取中心c) 的yS半col.bounds.extents.y
        Vector3 origin = col.bounds.center + new Vector3(0, -col.bounds.extents.y);
        //地板zy- 射(脑c, l向下l射 , 0.1f , 在第三layer)
        RaycastHit2D hit = Physics2D.Raycast(origin, Vector2.down, 0.1f, 1 << 3);
        Debug.DrawLine(origin,origin+ Vector3.down * 0.1f, Color.red , Time.deltaTime);
        //bool isgroundO限hit有]有zy到地面(或是任意colider)
        isground = hit.collider;
       
    }

    public void GetInput()
    {
        //GetAxisRaw樵谕婕逸入左或是右的r候返回(1,0)或是(-1,0)
        input_x = Input.GetAxisRaw("Horizontal");
        input_y = Input.GetKeyDown(KeyCode.Space);
    }

    public void DamageSelf()
    {
        currentHp -= 20;
        hpBar.value = currentHp / maxHp;
    }

    public void HealeSelf()
    {
        currentHp += 20;
        hpBar.value = currentHp / maxHp;
    }

    

    public void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.CompareTag(npcTag))
        {
            NPC npc = collision.GetComponent<NPC>();
            {
                npc.textBubbleAnim.SetBool("Appear", true); 
            }
        }
        if (collision.CompareTag(traptag) && maxHp > 0)
        {
            DamageSelf();

        }
        if (collision.CompareTag(goodtrap) && currentHp < 100)
        {
            HealeSelf();

        }
    }

    public void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag(npcTag))
        {
            NPC npc = collision.GetComponent<NPC>();
            {
                npc.textBubbleAnim.SetBool("Appear", false);
            }
        }
    }

  
    

}


