using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;

public class MyScript02 : MonoBehaviour
{
    //列表
    public List<Point2D> points = new List<Point2D>();

    //scrpit被加dr 绦幸淮
    private void Awake()
    {
        
    }

    // Start is called before the first frame update
    void Start()
    {
        //的造函
        //可以{用下面的 public Point2D() 或是 public Point2D(float xx , float yy)
        Point2D p1 = new Point2D(1.3f, 5.9f);
        Point2D p2 = new Point2D(1.7f, 6.0f);
        Point2D p3 = new Point2D(2.3f, 6.9f);

        //列表常用目
        //⑽矬w加入list中 Add(目); 加入序樽钗捕
        points.Add(p1);
        points.Add(p2);
        points.Add(p3);
        /*⑽矬wlist中h除 Remove(目);
        //points.Remove();
        //⑽矬w加入list中 Add(目); 加入序根序插入
        //points.Insert();
        print(points[2].x);
        //L
        型 名Q = L列表[第?].e面的l?
        */
        float point = points[2].x;

        //H使用枚e，是有c似可以M代a中的]
        Direction dog = Direction.East;
        Direction cat = Direction.North;

        if (cat == dog)
        {
            //xxxx
        }

        //每鼍把e面的目都是gameobject
        //每gameobject都是由很多M件(compoment)M成的
        //ctrl+d gameobject可以F似}u+拖拥牟僮

        gameObject.SetActive(true);
        gameObject.AddComponent<BoxCollider2D>();
        //GameObject.Destroy(gameObject);


        /*for (int i = 0;  i < 22 ;  i=i+2 )
        {
            GameObject go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.transform.position = new Vector3(i, 0, 0);
        }
        */

        //先定x一量型是SpriteRenderer 名Qsr 要get到@M件(GetComponent)把值x予o量 <尖括楂@取型>
        SpriteRenderer sr = GetComponent<SpriteRenderer>();
        sr.color = Color.red;

        //vector3用法
        Vector3 v = new Vector3(1f, 1f, 1f);
        Vector3 n = new Vector3(6f, 6f, 6f);

        //算c使用的
       float dist = Vector3.Distance(v, n);
        print(dist);

        //管理gameobject的位置、旋D、s放
        //只一transform就代表了前物w(unity自定x的)
        //改成物w位置至n
        //transform.position = n;
        //相於父物w的距x
        //transform.localPosition = new Vector3(3f, 3f, 3f);
        //相於父物w改前物w大小
        //transform.localScale = n;

        //transform""常用的方法
        //移x5
        transform.Translate(new Vector3(5, 0, 0));
        //@取子物w信息
        transform.GetChild(2).GetComponent<SpriteRenderer>().color = Color.black;
        transform.GetChild(2).GetComponent<Transform>().localPosition = new Vector3(2f, 0, 0);
        transform.GetChild(2).GetComponent<Transform>().localScale = new Vector3(3f, 3f, 0);

       
    }

    float timer = 0;
  
  

    //每0.02秒\行1次
    private void Update()
    {
        timer += Time.deltaTime;
        if(timer > 1)
        {
            print("meowmew");
            timer = 0;
        }

        if(Input.GetKeyDown(KeyCode.Q))
        {
            print("Quest");
        }

        if(Input.GetMouseButtonDown(0))
        {
            print("attack");
        }
    }

    //每M行1次
    private void FixedUpdate()
    {
        
    }

    /*
    大的(GameObject)轭
    小的(gameObject)楫前物w
    gameObject常用字段-> name tag layer transform

    gameObject常用方法
    1.setactive ⒂/不⒂梦矬w->第53列
    2.AddComponent <引用M件名Q>(); ->第54列
    3.Destroy Gameobject.destroy(gameobject) 摧物w ->第56列
    4.CreatePrimitive 建物w
    */

    /*class component
    1. get component


     */





}

public class Point2D
{
    //可以想像成工具，e的函t是工具的功能
    //是型，可以像是量一颖皇褂 
    //定xZ法 class 名Q {量c函}

    public float x;
    public float y;

    public Point2D()
    {

    }

    public Point2D(float xx , float yy)
    {
        this.x = xx;
        this.y = yy;
    }
}

//枚e是o"底"命名的方式
//本|就是可以L的列表，第一0...1..2 以此推
public enum Direction
{
    East,
    West,
    North,
    South,
}
