using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class review : MonoBehaviour
{
    // Start is called before the first frame update
    GameObject circle1;
    public GameObject circle2;
    public GameObject circle3;
    
    SpriteRenderer rd2;


    void Start()
    {
        //("B")需要被B建的|西是一定被知道的，是已知的 可以直接使用 名.函 名{用   例如:前物w的... transform.Translate
        //可以直接{用的，t不需要建例

        //在unity中找到特定tag的gameobject吧!
        circle1 = GameObject.FindGameObjectWithTag("Player");

        //一球{
        SpriteRenderer sr = circle1.GetComponent<SpriteRenderer>();
        sr.color = Color.blue;

        //A圈1移酉旅嬉桓
        circle1.transform.Translate(new Vector3(0, -6, 0));


        //A圈2移又A圈3的位置

        circle2.transform.position = circle3.transform.position;


        //A圈3的色更A圈1的色

        SpriteRenderer sr2 = circle3.GetComponent<SpriteRenderer>();
        sr2.color = sr.color;


        //}u一A圈1 位置在A圈1的上方

        GameObject clone = GameObject.Instantiate(circle1);
        clone.transform.Translate(new Vector3(0, 6, 0));


        rd2 = circle3.GetComponent<SpriteRenderer>();
      
    }

    
   

    // Update is called once per frame
    void Update()
    {
        //按下E按orh除A圈1

        if (Input.GetKeyDown(KeyCode.E)) 
        {
            GameObject.Destroy(circle1);
        }

        //按下r的r候A圈3不嘧殡SC色

        if (Input.GetKey(KeyCode.R))
        {
            rd2.color = new Color(Random.value , Random.value , Random.value);

        }

       


    }
}
