using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Square : MonoBehaviour
{
    


    void Start()
    {
        //gameobject中 "生成物w" "生成物wsphere"
       // GameObject.CreatePrimitive(PrimitiveType.Sphere);

        //c#基A概念-通常必要明一量後 才能去{用以及使用他

        //}目-⒎K色更改榧t色
        //先定x一量型是SpriteRenderer 名Qsr 要get到@M件(GetComponent)把值x予o量 <尖括轭型>
        // get到@SpriteRendererM件 把值xo量
        //在自身的物w上，去@取一  SpriteRenderer 型的 Component K且把@值o到左 "sr"的量e面
        //槭颤N可以@幼? 因 左的型是 SpriteRenderer 右的也是 SpriteRenderer 他是可以x值的
        SpriteRenderer sr = GetComponent<SpriteRenderer>();
        //sr目前代表了SpriteRendererM件
        sr.color = Color.red;



        /*
        for (int i = 0; i<50; i++)
        {
            GameObject go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.transform.position = new Vector3(i + 1, 0, 0);
        }
        */

    }

    public float exp = 0.01f;
    public float speed = 1;
    Vector2 input;
    Vector2 scale;
     

    private void Update()
    {
        if (Input.GetKey(KeyCode.W))
        {
            input.y = 1;
            input.x = 0;
          
        }
        else if (Input.GetKey(KeyCode.S))
        {
            input.y = -1;
            input.x = 0;
        }
        else if (Input.GetKey(KeyCode.A))
        {
            input.x = -1;
            input.y = 0;
            scale.x += exp;
            scale.y += exp;
        }
        else if (Input.GetKey(KeyCode.D))
        {
            input.x = 1;
            input.y = 0;
            scale.x += exp;
            scale.y += exp;
        }
        else
        {
            input.x = 0;
            input.y = 0;
            scale.x = 0;
            scale.y = 0;
        }



        //插入c的字不 按一下ins
        transform.Translate(new Vector3(input.x, input.y, 0)* speed * Time.deltaTime);
        transform.localScale = new Vector3(1+scale.x, 1+scale.y, 0); 
        
    }

    //大的gameobject- 可以理解念e面L
    //小的gameobject- 可以理解漠前物w(代a定的物品)
    

}
