using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SquareMove : MonoBehaviour
{
    //colider是心且有物理we的，被碰撞的
    //trigger是非心的

    //rigidbody的三N行槟Ｊ
    //1.Dynamic-完全⑴c物理模M-ex.掉落物
    //2.Kinematic-不主右樱需要用代a他移-ex.玩家移
    //3.Static-完全不移-ex.壁、地面
    //常用-gravity scale物件重力
    //Constraints-i定旋D
    //Material-控制力c摩擦

    //collision2d事件-enter2d(碰到r|l) exit2d(x_r|l) stay2d(碰撞r每捎|l)

    // Start is called before the first frame update

    public SpriteRenderer sr;
    public SpriteRenderer sr2;
    public GameObject ground;
    public GameObject triiger;

    int layermask = 1<<6;

    void Start()
    {
        

       

    }

    private void OnTriggerStay2D(Collider2D collision)
    {
        if (collision.gameObject == triiger)
            sr2.color = new Color(Random.value, Random.value, Random.value);
    }




    /*private void OnCollisionEnter2D(Collision2D collision)
    {
        if(collision.gameObject == ground)
        sr.color = new Color(Random.value, Random.value, Random.value);
        

    }
    */

    // Update is called once per frame
    void Update()
    {
        
    }
}
