using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UIManager : MonoBehaviour
{
    private string strAppear = "Appear";
    public GameObject uiPanel;
    public Animator anim;
    // Start is called before the first frame update
    void Start()
    {
        anim = uiPanel.GetComponent<Animator>();

        //Mathf.Lerp(float a, float b, float t); 性插值 取acb中g的t 如果a=0 b=10 t=0.7 那N取出的底=7
        //Mathf.Min(1.5f (a), 9.9f (b));  取acb之g 小的那担如果.Maxt取大的
       // Mathf.Clamp(float v, float min, float max); 底vO定mincmax之g 如果<mint=MinAttribute max同理>
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.P))
        {
            print("esc");
            ButtonClose(false);
        }
        if (Input.GetKeyDown(KeyCode.K))
        {
            print("esc");
            ButtonClose(true);
        }

    }

    public void ButtonClose(bool isActive)
    {
        anim.SetBool( strAppear, isActive);
    }
}
